name = "TerraFirmaGreg-Modern"
author = "Exception, Xikaro"
version = "0.13.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "686f056878f5693869146d5b6d94c1501ea3fef15ec8d618797ff0a85f983788"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
